### ISSUE TITLE
Some localizations not working on dedicated server (1.3.0 for 1.18.2 forge)

### ISSUE THREAD

**Issue by katubug** [Toma1O6/CollectorsAlbum#1]
Hi! I love this mod, but I'm having an issue with the localization in the hover-over tooltip, as you can see here:

![2022-10-26_10 50 03](https://user-images.githubusercontent.com/20935286/198074334-fdc8e34e-ef77-44cc-941e-d1e5bcebf218.png)

I am using:
Minecraft: 1.18.2
Forge: 40.1.84
Collector's Album: 1.3.0

This only happens on my server, not in singleplayer! So bizarre, I can't figure it out. Any ideas?

**Comment by Toma1O6** [comment]
Hi, that is kinda interesting issue. I'll take a look at it

**Comment by Toma1O6** [comment]
I have fixed the issue. It will be available in next release which should be ready within a week
