### ISSUE TITLE
[Request] Config to change benefits / rewards for filling out album

### ISSUE THREAD

**Issue by ConqAra** [Toma1O6/CollectorsAlbum#11]
Add a config that alters what you get from completing/filling out the album such as how much health you get from a health boost, and what effects you get from the album such as changing strength to haste instead and what level (e.g. haste 2, haste 3)

**Comment by Toma1O6** [comment]
This can be already configured via datapacks - https://github.com/Toma1O6/CollectorsAlbum/tree/releases/fabric/1.19.2/src/main/resources/data/collectorsalbum
