### ISSUE TITLE
[Bug] Mouse position gets reset

### ISSUE THREAD

**Issue by Dalethium** [Toma1O6/CollectorsAlbum#12]
When changing pages in the UI, the mouse position gets reset to the center of the screen. If you need more information to fix this please let me know!

Version: collectors-album-1.19.2-1.5.2.jar (fabric)

**Comment by Toma1O6** [comment]
This is done by minecraft on latest versions when opened container changes. Older versions did not have this issue

**Comment by Dalethium** [comment]
@Toma1O6 Could this not be forcably fixed though? Just setting the mouse position after the button is clicked? Or is that not advisable?

**Comment by Toma1O6** [comment]
It could be "fixed" if we kept the entire album logic in one container rather than having container per category. This would require some code rewriting and is not something we currently want to do

**Comment by Dalethium** [comment]
That's fair! Thanks for the quick replies by the way!
