### ISSUE TITLE
[Suggestion] Support for trinket slots

### ISSUE THREAD

**Issue by Dalethium** [Toma1O6/CollectorsAlbum#13]
It would be nice to be able to slot the book into fabric trinkets!

**Comment by Tr3c3** [comment]
Ditto for Curios, although it's possible for anyone to create a custom Curio slot for the album (or give the album an existing Curio tag), it'll stop providing buffs while equipped.

**Comment by Toma1O6** [comment]
Curios/Trinkets compatibility is now implemented starting with 2.0 versions of this mod
