### ISSUE TITLE
[Bug] Stacked cards can be moved to book

### ISSUE THREAD

**Issue by Dalethium** [Toma1O6/CollectorsAlbum#14]
With inventory convenience mods you can "space click" the cards into the book on fabric (which is very nice that it auto swaps out for the better cards!) -- if you have more than one card in a stack in your inventory, you can move a stack of cards (like, two legendary gold shovel cards) into the book. I don't think this is intended as it seems to only happen under specific circumstances.

If you need more info to fix this, please let me know!

Version: collectors-album-1.19.2-1.5.2.jar (fabric)

**Comment by Toma1O6** [comment]
Could you please provide more information about the "inventory convenience" mods? Because so far it looks like this is something done by the mods rather than the album itself. It should not be possible to insert more than one card into the slots by vanilla means

**Comment by Dalethium** [comment]
For sure! I believe it's inventory essentials v5.0.2, if you can't replicate the bug with that mod then please disregard this as the pack I am using has some 800-mods and I don't expect you to debug that.
