### ISSUE TITLE
[Suggestion] Forge - Curios Compatibility

### ISSUE THREAD

**Issue by kaz880** [Toma1O6/CollectorsAlbum#16]
I wonder if you were already planning on this, but that would be very cool if the album could fit in the curio like Time in a Bottle does without breaking the buffs. I saw some tried to make a custom slot for Curios, but the buffs went missing when in the Curios.

Also taking some time to tell you that this mod is wonderful and I love it! Keep up the good work! 💯🥇

**Comment by Toma1O6** [comment]
New version for 1.21 is now available with Curios compatibility (so far only for Neoforge as Forge does not have Curios for this version)

**Comment by kaz880** [comment]
Hey, out of curiosity, would you be open to make available for 1.20.1 as well?

**Comment by Toma1O6** [comment]
I am planning to backport the 2.0 version back to 1.20.1, however I am not sure when it will be done. But it is planned
