### ISSUE TITLE
BUG: Buffs disappear when open AE2 Controller

### ISSUE THREAD

**Issue by Colluttorio** [Toma1O6/CollectorsAlbum#17]
### **Mods:**
[Forge] collectors-album-1.20.1-1.5.5
Applied Energetics 2  v.15.2.4

### **How to replicate issue:**
1. Put into album enough cards to get buffs and let it into your inventory (no hotbar).
2. Place an AE2 Controller
3. Open AE2 Controller
4. The buffs of album disappear, like the album isn't yet present into inventory

PS: Thanks for your mod! It's amazing!

**Comment by Toma1O6** [comment]
Released 2.0 version of this mod with complete rewrite of all functionalities. This issue should now be resolved unless the AE2 controller forcefully replaces the inventory on player
