### ISSUE TITLE
[FABRIC 1.21] Client cannot join server

### ISSUE THREAD

**Issue by Hiusi** [Toma1O6/CollectorsAlbum#18]
When I add album mod I got this error when trying to join server, while on server there is no error only "Player joined" "Player disconnected"

Crash Report:
[disconnect-2024-08-09_15.28.22-client.txt](https://github.com/user-attachments/files/16558528/disconnect-2024-08-09_15.28.22-client.txt)

**Comment by Toma1O6** [comment]
Does it happen on every log in?
