### ISSUE TITLE
If you hit esc after opening a pack, you lose the cards (also some feedback)

### ISSUE THREAD

**Issue by katubug** [Toma1O6/CollectorsAlbum#2]
Hi! My friends and I have been playing with your mod on my server, and we've got a few suggestions, plus what I suspect is unintended behaviour.

Firstly, the bug is that if you hold to open a pack, but you don't click the cards to turn them over - the pack is still consumed, but you don't get anything. You just lose those cards.

We also have some feedback:

1. It would be nice to have an easier way of putting them into the book. Shift+click doesn't work, so that in particular would be nice. Or just "dropping" them onto the book from the inventory screen? I know that would be complicated once all slots were filled, though.
2. Opening cards is a bit slow. That's why I tried hitting esc, to see if it would automatically give me the cards. Don't get me wrong: I LOVE clicking them and hearing the little fanfares. It's incredibly satisfying and I still do that with the bigger card packs. But for lower-rank packs, I still want to open but more quickly.
3. **Having them sort in either numeric and/or rank order when using the auto-sort function** from other mods. This is the big one! We've either got to sort them manually before putting them into the book, or we have to hover over them a billion times to see which goes onto the current page. It's a little frustrating, and takes away from the satisfaction of the mod.

Thanks for the great mod, and for listening! Have a great day!

**Comment by Toma1O6** [comment]
Hi,
the bug you reported was actually wanted feature by @Tomano123CZ. We could possibly add config option for this though.

1) I could propably implement the shift click functionality in a way that it would be able to swap even already taken slots. 
2) You will be able to simply just Esc in the pack once the config option is added
3) The sorting may be interesting. What mods are you using for this? I could take a look if they provide some API for custom sorters, because otherwise I guess its sorted by name and that might be slighly complicated to implement currently.

Thanks for the feedback

**Comment by katubug** [comment]
Hi, thanks for the quick response! A config option would be great! I think
that would help a ton. And so would the shift+click functionality!

The sorters we currently use are Inventory Sorter and Quark (the Sort
Chest/Sort Inventory buttons). I haven't been able to figure out how they
sort the cards, it doesn't seem like there's any rhyme or reason to it! But
maybe I just haven't looked closely enough at it.

Hopefully there's an API! Thanks again for your time, and for the mod -
we're all really having fun with it.

**Comment by Toma1O6** [comment]
Regarding the sorting - I have implemented support for their sort system, so it should now sort the cards in the order you wanted. Config option will be also available for the partially opened card packages (you don't need to change anything, your wanted behaviour is set as default). And lastly, you will be able to move/swap cards using shift-click (the swap works only for cards which have higher rarity)

**Comment by katubug** [comment]
Amazing! Thank you for all your hard work! Both for this and for the other
issues. I appreciate you!
