### ISSUE TITLE
Please backport the mod to 1.20.1

### ISSUE THREAD

**Issue by JasdanVM** [Toma1O6/CollectorsAlbum#22]
This mod looks amazing, so I'd love to see it getting Backported to 1.20.1, as that version has most of the mods at the moment.

**Comment by Toma1O6** [comment]
I usually don't backport to older versions but it seems 1.20.1 is quite popular, so I'll see what can be done

**Comment by Toma1O6** [comment]
The 2.x version is now available on CurseForge with all features from 1.21
