### ISSUE TITLE
neoforge 1.20.1 crashed

### ISSUE THREAD

**Issue by ssakura49** [Toma1O6/CollectorsAlbum#25]
minecraft 1.20.1
neoforge 47.1.106

mods:
   configuration-forge-1.20.1-3.1.0.jar
   collectorsalbum-forge-1.20.1-2.1.3.jar

crash report:
   https://mclo.gs/iyByBt0

**Comment by Toma1O6** [comment]
Looks like NeoForge 1.20.1 is not fully compatible with all Forge mods as I thought. I will remove the NeoForge tag from CurseForge/Modrinth so that it is clear that it is not compatible with NeoForge on this version.
