### ISSUE TITLE
Effects don't seem to be working on dedicated server

### ISSUE THREAD

**Issue by katubug** [Toma1O6/CollectorsAlbum#3]
Hit enter too soon! Anyway, all my players are reporting that we don't seem to be getting any effects from our books. I am not sure how to help debug this, but please let me know if there's any logs or anything I can get you that might help. Thanks!

**Comment by Toma1O6** [comment]
Hi, I haven't been able to reproduce this issue on dedicated servers. We have also managed to test this successfully in LAN world with 3 players, so I'm not sure what could be the issue.
Are you certain that any conditions are fullfilled (like album having atleast 300 points / or having all cards in some categories)? Also you need to have the album in your inventory (and if you have multiple albums, they will conflict with eachother).

**Comment by Toma1O6** [comment]
Looks like this issue was present only on 1.18.2/1.19.2 Forge versions. I have fixed it and uploaded new version to curseforge. It should be available soon
