### ISSUE TITLE
[Suggestions] Make the effects configurable & Make a Page with Boost Info

### ISSUE THREAD

**Issue by katubug** [Toma1O6/CollectorsAlbum#4]
Hi! Me again, haha. We have been having great fun with your mod, but we think it might be a little overpowered as you finish your collection. For example, you literally cannot die to drowning because of the Regeneration.

Is it possible to make the effects configurable? It doesn't have to be anything fancy, but if I as a modpack maker can toggle certain effects on or off, that would be awesome. In a perfect world, getting to assign each effect as a modpack maker would be awesome - but I don't know how easy that would be.

Also, the tooltips which talk about the boosts cycle very quickly (and still don't seem to work on a server, they just don't show up?). Would it be possible to have a page inside the book which explains the boosts?

Thanks for reading! I hope you're having a good week so far.

**Comment by Toma1O6** [comment]
Hi, about the fast description - I have noticed it too, but for some reason it happens only when Quark mod is installed, so I guess its something related to the mod (it also affected speed at which new vanilla recipes pop up in upper right corner).
I'll look again into the issue with missing effects on server, but last time I was able to test it successfully on dedicated server 🤔.

And finally, regarding the boost configuration - the option is already here, via datapacks. If you know how to create datapacks, then you can take look at default implementation here: https://github.com/Toma1O6/CollectorsAlbum/tree/releases/fabric/1.19.2/src/main/resources/data/collectorsalbum/card_boosts

**Comment by katubug** [comment]
Hi! It's interesting that it's a quark incompatibility! That's frustrating.

And the effects work! Sorry, I phrased poorly. The effects are working, but
the tooltips just don't show up on a server. I can't imagine why, but I
wonder if that's also Quark 😂

And oh okay! I am somewhat familiar with data packs, I'll check out that
link now. Thank you so much!

**Comment by Toma1O6** [comment]
I have fixed these issues in latest release, it should be available soon on curseforge
