### ISSUE TITLE
[1.18.2] [Fabric] Incompatible with Forgotten Graves

### ISSUE THREAD

**Issue by ConqAra** [Toma1O6/CollectorsAlbum#5]
Crashes on launch when loaded with [Forgotten Graves](https://github.com/ginsm/forgotten-graves) mod

[Crashlog](https://paste.ee/p/ruwOw)

**Comment by Toma1O6** [comment]
I'll fix it in next release

**Comment by Toma1O6** [comment]
New version is being currently uploaded to curseforge, it should be available soon
