### ISSUE TITLE
Client to server handshake trouble

### ISSUE THREAD

**Issue by Zelioth** [Toma1O6/CollectorsAlbum#7]
Mod Pack : Friends United Fabricated
Minecraft Version : 1.19.2
Fabric latest version 0.14.10
Collectors Album 1.5.0

Appears some sort of error while connecting to the public server for our mod pack. it gives this crash report and I think it is saying that collectors album update is at fault
[crash-2022-11-15_18.42.43-client.txt](https://github.com/Toma1O6/CollectorsAlbum/files/10017267/crash-2022-11-15_18.42.43-client.txt)

**Comment by Toma1O6** [comment]
I found the issue, I'll prepare fix later today

**Comment by UdoMorgenstern** [comment]
same crash happens on forge
MC 1.19.2 
Forge: 43.1.52
Collectors Album 1.5.0

only happens for users holding an album
[crash-2022-11-14_08.58.55-client.txt](https://github.com/Toma1O6/CollectorsAlbum/files/10019693/crash-2022-11-14_08.58.55-client.txt)

downgrade to Collectors Album 1.4.0 resolved the issue

**Comment by Toma1O6** [comment]
Issue has been resolved and fix tested on dedicated server without issues. Version 1.5.1 should be available on curseforge soon
